# Generated by Django 4.1.7 on 2023-03-28 00:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_item_brand_alter_item_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
