# Generated by Django 4.2 on 2023-04-18 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_coupon_id_alter_coupon_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='expired_at',
            new_name='expire_by',
        ),
    ]
