# Generated by Django 4.2 on 2023-04-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_expired_at_coupon_expire_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
