# Generated by Django 4.2 on 2023-04-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_order_refund_granted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
