# Generated by Django 4.2 on 2023-04-21 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_order_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
    ]
