# Generated by Django 4.1.7 on 2023-03-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
    ]
