# Generated by Django 4.1.7 on 2023-03-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_address_address_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='age',
            new_name='birthday',
        ),
    ]
