# Generated by Django 4.1.7 on 2023-03-26 23:51

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_age_profile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile-pics/default.png', upload_to=user.models.user_dir_path),
        ),
    ]
